/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class springboot_jni_JniApi */

#ifndef _Included_springboot_jni_JniApi
#define _Included_springboot_jni_JniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     springboot_jni_JniApi
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_springboot_jni_JniApi_testHello
  (JNIEnv *, jclass);

/*
 * Class:     springboot_jni_JniApi
 * Method:    certificateValidation
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_springboot_jni_JniApi_certificateValidation
  (JNIEnv *, jclass, jstring);

/*
 * Class:     springboot_jni_JniApi
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_springboot_jni_JniApi_encrypt__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     springboot_jni_JniApi
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_springboot_jni_JniApi_decrypt__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     springboot_jni_JniApi
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_springboot_jni_JniApi_encrypt__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     springboot_jni_JniApi
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_springboot_jni_JniApi_decrypt__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
